# Generated by Django 5.0.6 on 2024-06-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='pickup_time',
            new_name='pickup_date_time',
        ),
    ]
